# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HiddenCard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HiddenCard
  pod 'RIBs'
  pod 'Texture'
  pod 'TextureSwiftSupport'
  pod 'RxCocoa-Texture'
  pod 'GTTexture-RxExtension'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'SnapKit'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'

  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/OAuth' # Used for Sign in with Apple, Twitter, etc
  pod 'FirebaseUI/Phone'
  
  target 'HiddenCardTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'

  end

  target 'HiddenCardUITests' do
    # Pods for testing
  end

end
